# Generated by Django 6.1.1 on 2026-10-06 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(help_text='Ejemplo: Canelo, Arrayán, Manolito, etc.', max_length=100)),
                ('nombre_cientifico', models.CharField(help_text='Ejemplo: Drimys winteri, Luma apiculata, etc.', max_length=100)),
                ('metodo_cultivo', models.CharField(choices=[('MACETA', 'En maceta (sustrato)'), ('AGUA', 'En agua'), ('SUELO', 'Directo en suelo')], help_text='Selecciona el método de cultivo de la planta.', max_length=20)),
                ('ubicacion_casa', models.CharField(help_text='Ejemplo: Ventana, Cocina, Dormitorio, etc.', max_length=100)),
                ('fecha_plantacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RIEGO', 'Riego / Cambio de agua'), ('RAIZ', 'Brote de raíces nuevas'), ('HOJA', 'Brote de hojas nuevas'), ('ABONO', 'Aplicación de abono / fertilizante'), ('PODA', 'Poda de hojas o raíces')], help_text='Selecciona el tipo de evento de cuidado realizado.', max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Ej: Salió la primera raíz de 1 cm en agua')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='botanica.planta')),
            ],
        ),
    ]
